### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by MS-PC2** [Project-Nagisa/Nagisa#3]
My question is a download manager that speeds up the download?
Software example:
"Internet Download Manager"

Conclusion: "speed up downloads" or "simply manage downloads without accelerating".
"I would appreciate your response".

**Comment by MouriNaruto** [comment]
Download managers like IDM can speed up the download in some scenarios. 

I hope my project can bring everyone a better download experience and I will try my best.

Mouri
