### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by gbjbgdhjhd** [Project-Nagisa/Nagisa#5]
好长时间没更新了，Build会也开完了，快更新了吧？

**Comment by MouriNaruto** [comment]
今天买了台新的笔记本，于是可以加速开发了（因为自己的旧笔记本和实验室的台式机配置都很烂）

我当时只是说Build大会之后开始开发，事实上我也做到了，把下载库部分用C++/WinRT重写了一遍

然后现在可以安心的给下载库加功能了

**Comment by MouriNaruto** [comment]
当然为了不让你们着急等待，我打算最近推送一个版本
虽然没有加入自己写的下载引擎，但是代码是重构过的

**Comment by uaena888** [comment]
感谢大神，希望加上多线程和BT下载

**Comment by MouriNaruto** [comment]
@uaena888 这是必须要做的事情

**Comment by MouriNaruto** [comment]
关于Nagisa未来要实现的功能，详见 https://github.com/Project-Nagisa/Nagisa/issues/6

@gbjbgdhjhd @uaena888
